### ISSUE TITLE
Documentation improvments

### ISSUE THREAD

**Issue by galuszkak** [blacktorn/django-storage-swift#17]
Hi @blacktorn ,

I think It's crucial to mention about those properties in documentation:
SWIFT_NAME_PREFIX
SWIFT_STATIC_NAME_PREFIX
SWIFT_STATIC_BASE_URL

They aren't documented and this will help a lot when someone looks on this first time. :)

Thanks for good work!

**Comment by blacktorn** [comment]
Added in 3ff2fcc652598845bb7fa538ce67d733fa64d347

Thanks!
