### ISSUE TITLE
collectstatic --clear doesn't work

### ISSUE THREAD

**Issue by galuszkak** [blacktorn/django-storage-swift#18]
`manage.py collectstatic --clear` doesn't work because of lack of implementation of listdir method.

    File "/home/fanimani/.virtualenvs/live/local/lib/python2.7/site-packages/django/core/files/storage.py", line 110, in listdir
    raise NotImplementedError('subclasses of Storage must provide a listdir() method')

    NotImplementedError: subclasses of Storage must provide a listdir() method

**Comment by blacktorn** [comment]
This should work now since #19 is merged.

**Comment by galuszkak** [comment]
@blacktorn thanks! :+1:
