### ISSUE TITLE
issues with v2 auth?

### ISSUE THREAD

**Issue by corn13read** [blacktorn/django-storage-swift#23]
I'm attemping to use this with the swift all in one VM. I had previously had v1 working with the swift-docker and that was dandy but getting keystone set up was kind of a nightmare. In the SAIO VM keystone exists and I was able to get collectstatic to work fine but then when I go to the admin page I will give media urls like this:

188.24.23.175:8080/v2/AUTH_addeb456bae4484081dc53da36d57844/django-static/admin/css/login.css 

and visiting the link will yield: 
Authentication required

Any help would be appreciated. How are others testing this with swift? Anyone know of a good VM or docker that just works with both auths?

**Comment by masterdubs** [comment]
Hi, put your Swift container public un openstack directly.

**Comment by blacktorn** [comment]
@corn13read did the suggestion by @masterdubs fix your issue?

**Comment by einarf** [comment]
Close this one? :)
