### ISSUE TITLE
populating a FileField with a url, rather than uploading the file contents

### ISSUE THREAD

**Issue by klrmn** [blacktorn/django-storage-swift#25]
My django app is going to be using a RESTful API to populate the FileField on my model. I definitely want to be able to _read_ files from swift, but I'd rather be able to create them by uploading a url to an existing object in swift, and save half the network traffic. Do you know of any mechanism that would allow me to do this?

**Comment by klrmn** [comment]
also, does this middleware stream or spool the files?

**Comment by einarf** [comment]
@blacktorn Might be time to close as no one have really followed up on this one.
