### ISSUE TITLE
I set swift container private and used TEMP_URL to get file but swift server responsed "401 Unauthorized: Temp URL invalid"

### ISSUE THREAD

**Issue by stand1921** [blacktorn/django-storage-swift#26]
Help!
My django-storage-swift setting is:
    DEFAULT_FILE_STORAGE = swift.storage.SwiftStorage
    STATICFILES_STORAGE = swift.storage.StaticSwiftStorage
    COMPRESS_STORAGE = STATICFILES_STORAGE
    SWIFT_AUTH_URL = http://10.240.0.10:5000/v2.0
    SWIFT_USERNAME = wangyuqi
    SWIFT_KEY = wangyuqi
    SWIFT_AUTH_VERSION = 2
    SWIFT_TENANT_NAME = wangyuqi
    SWIFT_TENANT_ID = 233146f86bc740e09e06986a8e2a0d65
    SWIFT_CONTAINER_NAME = file
    SWIFT_STATIC_CONTAINER_NAME = static1
    SWIFT_AUTO_CREATE_CONTAINER = True
    SWIFT_BASE_URL = http://10.240.0.10:8080
    SWIFT_USE_TEMP_URLS = True
    SWIFT_TEMP_URL_KEY = '1234567890'
    SWIFT_TEMP_URL_DURATION = 30*60

they have been all set

And then I came into my website, the static file doesn‘t work.

I use the website page source's url "http://10.240.0.10:8080/v1/AUTH_233146f86bc740e09e06986a8e2a0d65/static1/img/zlogo_new.png?temp_url_sig=ddd05c1a5b16f40de8e44409273502151dd21905&temp_url_expires=1438592473" to download the static file. The swift server responsed "401 Unauthorized: Temp URL invalid"

10.240.0.10 is the swift server IP.

**Comment by blacktorn** [comment]
Were you able to solve this problem?

**Comment by bzmwillemsen** [comment]
@stand1921 just a bump on this, I'm experiencing the same issue.

**Comment by stand1921** [comment]
@bzmwillemsen I haven't solve this issue yet. And looks like I don't need to. Swift is too slow, so we need to use CDN on it, and CDN don't support the swift's temp URL.
