### ISSUE TITLE
Stop configuration from being dependent on settings.py

### ISSUE THREAD

**Issue by 9cloud** [blacktorn/django-storage-swift#30]
I'd suggest moving the settings for all the variables like api_auth_url into __init__ just like how s3boto.py in Django-storages does it.

This way you can have a multiple swift containers... which is useful if you ever have to transfer from one hosting company to another or even just transfer between projects.

**Comment by blacktorn** [comment]
Pulled in the changes by @biern that added this exact functionality.

**Comment by omarkhan** [comment]
This is great, thanks! Any chance you could cut a release with this @blacktorn?

**Comment by blacktorn** [comment]
@omarkhan Version 1.2.7 is now on PyPI!

**Comment by omarkhan** [comment]
Excellent, thank you @blacktorn!
