### ISSUE TITLE
Content already seeked

### ISSUE THREAD

**Issue by zacbri** [blacktorn/django-storage-swift#34]
Ok, that's an odd one : 

on a local instance everything's fine and the files are correctly saved.
But on an instance running behind a proxy (Nginx), the _save method receives a content that has already been seeked.
Therefore, the object pushed to Swift has a size of 0 bytes.

I had to inherit from SwiftStorage and perform a content.seek(0) before calling _save() to get the file to properly upload.
Have you ever come across this ?

**Comment by blacktorn** [comment]
Didn't come across that yet, but I'm not yet running the latest version in production.
Will have to test that later today on a site.

**Comment by blacktorn** [comment]
I've tested it on one of my websites and it's all working, what were you trying to do when you got the error?

For me uploading and creating thumbnails which were also uploaded to swift all worked.

**Comment by zacbri** [comment]
Well I'm not sure how to explain it...
I'm basically uploading files through Django Rest Framework.

The application code doesn't touch the 'InMemory' file before it gets to the storage backend's _save() method.
In fact when hitting the API directly (app running with manage.py's runserver) everything's fine.
But when the app is running on Gunicorn behind Nginx, the file descriptor passed to _save() gives a 0 bytes content when a read() is performed.
If I do a content.seek(0) on it before calling SwifStorage._save() it is fine.

It does look like it has something to do with my setup, so I'll have to test more and see if it is related to Gunicorn.
I'm happy with my current workaround for now (I had to inherit from SwiftStorage for other reasons anyway).

Thanks for looking into this, I'll let you know what I find :)

**Comment by bzmwillemsen** [comment]
I am also experiencing this same issue. I had to do this:

```
class SuperSwiftStorage(SwiftStorage):

    def _save(self, name, content):
        # Workaround to fix seek issue.
        content.seek(0)
        return super(SuperSwiftStorage, self)._save(name, content)

```

**Comment by bzmwillemsen** [comment]
To give more context to this, the S3BotoStorage library "rewinds" all of the content that is passed to the `_save` library.

**Comment by blacktorn** [comment]
I can probably add the `content.seek(0)`, don't think it should fail if the pointer is already on 0.
