### ISSUE TITLE
Upload objects with public read permissions by default?

### ISSUE THREAD

**Issue by ajtaylor6** [blacktorn/django-storage-swift#35]
When using django-storage-swift with the 'collectstatic' command, targeting a publically read-able container, all of the objects look to be uploaded as private/restricted read. Is there an option I'm missing to make sure objects get uploaded with fully allowed read permissions?

**Comment by einarf** [comment]
A bit late to answer now, but here it is:

You probably used the `SWIFT_AUTO_CREATE_CONTAINER`. If you also need the container to be public you need to include the `SWIFT_AUTO_CREATE_CONTAINER_PUBLIC` option. And make sure the container sets CORS headers using `SWIFT_AUTO_CREATE_CONTAINER_ALLOW_ORIGIN` so browsers don't freak out.

**Comment by einarf** [comment]
@blacktorn This is documented and working, so not an issue any more.
