### ISSUE TITLE
Bluemix object storage

### ISSUE THREAD

**Issue by dinopetrone** [blacktorn/django-storage-swift#36]
I'm attempting to integrate with bluemix's object storage and i'm not able to find the right way to map object storage's env variable to the correct django settings.  
For the following env vars:
![Sample](https://www.evernote.com/l/AfeQnXwI_ClHFom7ie6Oi-0Wo3E12Knro1kB/image.png "Sample")
How do you go about mapping this to a the right Django settings?  If you push me in the right direction, i'd be happy to assist in updating your projects docs via pull request.  Thanks in advance.

**Comment by blacktorn** [comment]
You could try something like this:
``` python
SWIFT_AUTH_URL = '<auth_url>/v3'
SWIFT_AUTH_VERSION = 3
SWIFT_USERNAME = '<userId>'
SWIFT_KEY = '<password>'
SWIFT_TENANT_NAME = '<projectId>'
SWIFT_CONTAINER_NAME = '<container_name>'
SWIFT_EXTRA_OPTIONS = {
    'region_name': '<region>',
}
DEFAULT_FILE_STORAGE = 'swift.storage.SwiftStorage'
```

Don't know if this is correct, don't have a test bluemix object storage instance to test it.
Here is an example for the raw swiftclient implementation that might help:
https://www.ibm.com/developerworks/community/blogs/1b48459f-4091-43cb-bca4-37863606d989/entry/Use_Python_to_access_your_Bluemix_Object_Storage_Service_with_Keystone_v3?lang=en

**Comment by dinopetrone** [comment]
Thanks so much for the quick response @blacktorn 
The link you sent helped me get it buttoned up.  Here is the code for anyone else running into this in the future:

```
VCAP_SERVICES = environ.get('VCAP_SERVICES', "")
bluemix_env = json.loads(VCAP_SERVICES)
object_storage = bluemix_env.get('Object-Storage', [{}])[0]
object_storage_creds = object_storage.get('credentials', {})

SWIFT_AUTH_URL = "{}/v3".format(object_storage_creds.get('auth_url'))
SWIFT_USERNAME = object_storage_creds.get('userId')
SWIFT_KEY = object_storage_creds.get('password')
SWIFT_STATIC_CONTAINER_NAME = SWIFT_CONTAINER_NAME = "kpdev"
SWIFT_AUTH_VERSION = 3

SWIFT_EXTRA_OPTIONS = {
    "project_id": object_storage_creds.get('projectId'),
    "user_id": SWIFT_USERNAME,
    "region_name": "dallas"
}

STATICFILES_STORAGE = 'swift.storage.StaticSwiftStorage'
DEFAULT_FILE_STORAGE = 'swift.storage.SwiftStorage'
```

obviously note that kpdev is a container i made manually first.  Thanks again!

**Comment by mohibJV** [comment]
@dinopetrone how did you change the static url/media url to point to the container?

**Comment by dinopetrone** [comment]
@mohibJV  yes you have to override STATIC_URL.  

it looks something like this:
```
STATIC_URL = "https://dal.objectstorage.open.softlayer.com/v1/AUTH_{}/{}/".format(
    OBJECT_STORAGE_PROJECTID, SWIFT_STATIC_CONTAINER_NAME)
```

**Comment by jancsarc** [comment]
Are these settings still working for you @dinopetrone ?
