### ISSUE TITLE
Omitting SWIFT_CONTAINER_NAME gives a very unhelpful error

### ISSUE THREAD

**Issue by tino** [blacktorn/django-storage-swift#37]
I spent quite some time digging into the python `urlib.parse.quote` source code because I got the following error and could not understand why it would happen:

`TypeError: quote_from_bytes() expected bytes`

As it turned out (thanks to some pdb'ing), `SWIFT_CONTAINER_NAME` get's set to `None` if you don't define it, and `quote()` happily accepts that, but `quote_from_bytes()` doesn't.

Changing https://github.com/blacktorn/django-storage-swift/blob/master/swift/storage.py#L39 to:
`container_name = setting('SWIFT_CONTAINER_NAME', '')`
creates an error that is a little bit better, but it would be better to raise errors on absent required parameters. Suggestions? Then I'll create a pull request.

**Comment by blacktorn** [comment]
The Django check framework might be a nice solution to the unhelpful error messages:
https://docs.djangoproject.com/en/1.9/topics/checks/

What do you think?

**Comment by tino** [comment]
That's a possibility, but seems like a lot of boilerplate. Wouldn't looping through all required settings in the '__init__'  and raising ImproperlyConfigured on a missing one be easier and accomplish the same?

**Comment by blacktorn** [comment]
Anything is fine by me, just thought of that framework as then all error messages appear at the same place.

**Comment by binarysubstrate** [comment]
+1

**Comment by einarf** [comment]
This issue should be closed
