### ISSUE TITLE
Few errors while accessing the URL  

### ISSUE THREAD

**Issue by swanandM** [blacktorn/django-storage-swift#40]
Hello, Here are some errors which I faced while installing. Please help. Thanks in advance.

![screenshot 197](https://cloud.githubusercontent.com/assets/10551803/15482913/d22ed3b2-20f7-11e6-8f5d-e40e128632db.png)

When I am trying to access "http://127.0.0.1:8000/admin/ "

![screenshot 198](https://cloud.githubusercontent.com/assets/10551803/15482980/1ded2088-20f8-11e6-9ae5-767c404c2a28.png)

When I am trying to access "http://127.0.0.1:8000/

![screenshot 199](https://cloud.githubusercontent.com/assets/10551803/15483142/d5882544-20f8-11e6-897d-cd7fb3ee3f65.png)

It showed me above error when I ran this command --- python manage.py collectstatic --noinput

**Comment by einarf** [comment]
I'm guessing you just copied the example configuration. `SWIFT_AUTH_URL` needs to point to an authentication endpoint. There is apparently no such service running on `http://127.0.0.1:8080/auth/v1.0`.

**Comment by einarf** [comment]
@blacktorn Probably time to close this one 😄
