### ISSUE TITLE
listdir error

### ISSUE THREAD

**Issue by flo-dhalluin** [blacktorn/django-storage-swift#41]
startswith first arg must be str or a tuple of str, not list
```

/usr/local/lib/python3.4/site-packages/swift/storage.py in listdir

                if not obj['name'].startswith(path):

     ...

```

again, pull request incoming

**Comment by e-kolpakov** [comment]
@blacktorn  **tl;dr**: are there any chance you're releasing next version (1.2.10 or 1.3.0) any time soon (like this week?)

My team have three significant PRs (https://github.com/edx/configuration/pull/2723, https://github.com/edx/edx-platform/pull/11286 and https://github.com/edx/xqueue/pull/103) pending, and I've just discovered that one of those are blocked by this issue.

We're using 1.2.9 from PyPi, and if I understand right it is the latest version on PyPi and latest git tag available.

It would be great if you could push newer version to PyPi or at least make a new git tag this week - we're somewhat limited in time to land those PRs. If you have any concerns about making a new version now we can handle it in a different way (i.e. pin dependency to git commit), but we'd rather use PyPi version.

**Comment by blacktorn** [comment]
@e-kolpakov Sure thing, version 1.2.10 is now up on PyPI, sorry for the delay!

**Comment by e-kolpakov** [comment]
@blacktorn Awesome, thank you!
