### ISSUE TITLE
Cannot use URL created for filename returned by SwiftStorage._save()

### ISSUE THREAD

**Issue by haikuginger** [blacktorn/django-storage-swift#49]
The issue is that the filename returned by SwiftStorage._save (and others) contains the path prefix. However, when going to open those files or create URLs for those files, the path prefix gets re-prepended. My suggestion is to replace areas where we have 

```python
if self.name_prefix:
    name = self.name_prefix + name
```

with

```python
if self.name_prefix and not name.startswith(self.name_prefix):
    name = self.name_prefix + name
```

This will preserve current behavior in most cases, but prevent us from doubling up on the name prefix.

If that sounds good, I can submit a PR later today.

**Comment by blacktorn** [comment]
Sounds good to me! 👍🏻

**Comment by haikuginger** [comment]
After some internal discussion, we think the better way might be for `django-storage-swift` to simply return filenames with the prefix omitted. This wouldn't solve for existing cases, but would solve the problem going forward and have more predictable behavior. I'm updating my PR to do that.
