### ISSUE TITLE
New pip release?

### ISSUE THREAD

**Issue by zacbri** [blacktorn/django-storage-swift#51]
Hi @blacktorn 

any chance you could release a new version to Pypi with the recent fix for Django 1.10?
This way we won't have to depend on our fork.

Thanks!

**Comment by pchinea** [comment]
Hey @blacktorn 

Please, I'm also waiting for it.

Thanks!

**Comment by krailler** [comment]
Release please @blacktorn, my porn application is waiting for you...

**Comment by fluxsc2** [comment]
I need the same release too! @blacktorn

**Comment by blacktorn** [comment]
I've just uploaded v1.2.11

**Comment by zacbri** [comment]
Awesome, thanks !
