### ISSUE TITLE
ImportError: No module named deconstruct

### ISSUE THREAD

**Issue by omarali** [blacktorn/django-storage-swift#54]
This error happens with django versions older than 1.7 (https://docs.djangoproject.com/en/1.10/releases/1.7/#new-method-on-field-subclasses).

```
>>> import swift.storage
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/swift/storage.py", line 11, in <module>
    from django.utils.deconstruct import deconstructible
ImportError: No module named deconstruct
>>> import django
>>> django.VERSION
(1, 6, 11, 'final', 0)
```

One solution is to use an identity decorator if django.utils.deconstruct cannot be imported to maximize support across as many django versions as possible.

```
-from django.utils.deconstruct import deconstructible
+try:
+   from django.utils.deconstruct import deconstructible
+except ImportError:
+   def deconstructible(arg):
+      return arg
```

**Comment by einarf** [comment]
I guess the best way is to make a PR with a suggested solution. I'm not entirely sure what Django version this project aims to support, but looking at the recently created tests it seems that django 1.9 and 1.10 is the main focus. (aka. currently supported versions by the django project)

**Comment by omarali** [comment]
Opened PR #71.
