### ISSUE TITLE
Unable to set STATIC_URL

### ISSUE THREAD

**Issue by Austriker** [blacktorn/django-storage-swift#55]
Hi,

I have set up the django storage swift following the guide, but when I deploy I am having trouble with the static url.
The server tries to get the static from the local server and not the distant storage `/v1/auth....` and not `https://storage.sbg1.cloud.ovh.net/v1/auth...`

Here is my settings : 

``` python
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATIC_PATH = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    STATIC_PATH,
)

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

# Media files
MEDIA_ROOT = os.path.join(
    BASE_DIR,
    'media',
)
MEDIA_URL = '/media/'

DEFAULT_FILE_STORAGE = 'swift.storage.SwiftStorage'
STATICFILES_STORAGE = 'swift.storage.StaticSwiftStorage'

SWIFT_AUTH_URL = 'https://auth.cloud.ovh.net/v2.0/'
SWIFT_AUTH_VERSION = '2'

SWIFT_TENANT_ID = ''
SWIFT_TENANT_NAME = ''

SWIFT_CONTAINER_NAME = 'testmedia'
SWIFT_STATIC_CONTAINER_NAME = 'teststatic'

SWIFT_USERNAME = ''
SWIFT_KEY = ''

SWIFT_EXTRA_OPTIONS = {
    "region_name": "SBG1",
}
```

I tried adding `STATIC_URL = "https://storage.sbg1.cloud.ovh.net/"` to the settings but it doesn't change anything.

The admin template doesn't work also. I checked on the bucket the static files are there.

Thanks for your help.

**Comment by einarf** [comment]
I have the same issue after the .12 release. Trying to figure out what is going on.

**Comment by einarf** [comment]
I got i working by turning off auto base url. There is something that mangles the base url when this is enabled.
```
SWIFT_AUTO_BASE_URL = False
```
Then I had to specify explicit base urls both for media and static
```
SWIFT_BASE_URL = <full url including container name ending with />
SWIFT_STATIC_BASE_URL = <full url including container name ending with />
```

Setting `STATIC_URL` is really only useful if you have urls in css that still refers to `/static/` and will cause a redirect to the correct url in swift.

**Comment by einarf** [comment]
I fixed it in #57

**Comment by einarf** [comment]
@Austriker I think you can bypass with bug by setting:

```
SWIFT_STATIC_BASE_URL = None
```

Then the backend will not try to mangle the `base_url` returned from swift.

**Comment by einarf** [comment]
Use 1.2.13 release or later. Also feel free to close this one :)
