### ISSUE TITLE
Missing a simple test suite

### ISSUE THREAD

**Issue by einarf** [blacktorn/django-storage-swift#58]
It would be nice if the project had a simple test suite using travis and tox. We could start with something simple. I'll see if I can find time to add something basic soon. It's fairly straight forward to set up.

I'm guessing running tox with for example py27 and py35 would be a good start + basic tests instantiating the backend with common parameters for v2 and v3 auth.

**Comment by einarf** [comment]
There is a working tox run with a dummy test now at least :)

I'm guessing a good start is to mock the swift client itself and start testing configuration.

**Comment by blacktorn** [comment]
Do you have an example how to do that?
I've never really done that myself, this will be my first project with tests to be honest.

I've just pushed an update to the travis config to add the isort and flake8 checks.

**Comment by einarf** [comment]
@blacktorn I'm definitely also not an expert, but I can give it a go. The `unittest` package have some powerful tools for modifying modules, classes etc.

**Comment by einarf** [comment]
We can look into mocking the actual swift client in the future, but having a fake client for now means we can at least write tests that will still be valid in the future.

**Comment by einarf** [comment]
We got more than basic testing now.
