### ISSUE TITLE
REGION_NAME not configurable

### ISSUE THREAD

**Issue by valerytschopp** [blacktorn/django-storage-swift#77]
We have a multi-region OpenStack deployment, but it is not possible to configure the `OS_REGION_NAME` for the Django Swift Storage.

A new `SWIFT_REGION_NAME` parameter is required.

**Comment by valerytschopp** [comment]
There a workaround for this. 

Using the `SWIFT_EXTRA_OPTIONS` to set the region name like this:

    SWIFT_EXTRA_OPTIONS = { 
      'region_name': 'MY_SECOND_REGION'
     }

But it would be more consistent with OpenStack to add a new `SWIFT_REGION_NAME` parameter.

**Comment by einarf** [comment]
Definitely. Specifying region name is a natural part of authentication in OpenStack, so having a parameter for it is good.

**Comment by einarf** [comment]
Lunch commit #78

**Comment by einarf** [comment]
@valerytschopp It's merged, so you can close this one.

**Comment by blacktorn** [comment]
It's also on [PyPI](https://pypi.python.org/pypi/django-storage-swift/1.2.16)

**Comment by valerytschopp** [comment]
Thanks a lot for adding the `SWIFT_REGION_NAME` config parameter, and releasing it
