### ISSUE TITLE
401 Unauthorized: Temp URL invalid if path contains whitespaces

### ISSUE THREAD

**Issue by dperetti** [blacktorn/django-storage-swift#79]
Obviously a quoting issue.
Suggestion : refactor url() using swiftclient's [generate_temp_url()](https://github.com/openstack/python-swiftclient/blob/3934bd606acc2333ee9ae63a40baa35928ef908d/swiftclient/utils.py#L65).

FYI my quick and dirty workaround in my django app was as follow :

    from swiftclient.utils import generate_temp_url
    from six.moves.urllib import parse as urlparse

    sw = SwiftStorage()
    url = urlparse.urljoin(sw.base_url, urlparse.quote(sw.name_prefix + release_path))
    path = urlparse.unquote(urlparse.urlsplit(url).path)
    url = generate_temp_url(path=path, key=sw.temp_url_key, seconds=int(sw.temp_url_duration), method='GET')
    return urlparse.urljoin(sw.base_url, url)

**Comment by einarf** [comment]
Got an example of an invalid url?

**Comment by einarf** [comment]
Please review the PR

**Comment by dperetti** [comment]
Will let you know shortly !

**Comment by einarf** [comment]
Great. Not sure if the quoting matters or not. That's the only thing missing from your example.

**Comment by dperetti** [comment]
Trying to pip install your pull request like usual and this doesn't work:

    pip install git+git://github.com/blacktorn/django-storage-swift.git@043fabe1af9532f9b5d649ef450abf0d75616802

Says it's not a tree. Any idea ?

**Comment by einarf** [comment]
Try from the repo/branch the pull requests came from:
https://github.com/ZettaIO/django-storage-swift/tree/temp-url

**Comment by einarf** [comment]
To be more specific, use github's archive url: (tar.gz of branch temp-url)
https://github.com/ZettaIO/django-storage-swift/archive/temp-url.tar.gz

**Comment by dperetti** [comment]
Using your fork works ... but I'm back to 401 !
The url seems OK but the temp_url_sig is probably wrong.
It looks like you pass the sig as third argument of generate_temp_url, it should be an url_key as in my example above.

**Comment by einarf** [comment]
When do you get 401?

**Comment by dperetti** [comment]
When I go to the generated url.

**Comment by einarf** [comment]
Are you sure that added the `SWIFT_TEMP_URL_KEY` in your swift account as well?

**Comment by dperetti** [comment]
Of course, look at my example, I'm even using it and... it works.
Again, I think you don't pass the correct arguments to `generate_temp_url()`. Read [this](http://docs.openstack.org/developer/python-swiftclient/swiftclient.html#swiftclient.utils.generate_temp_url) : the third argument should precisely be the temp url key, not the hash of it !

**Comment by einarf** [comment]
ahh yes you are right. `generate_temp_url` is also generating the hmac.

Fixing.

**Comment by dperetti** [comment]
Side comment : the unit tests should have spotted that it didn't work ;-)

**Comment by einarf** [comment]
Yep they should ideally do that. Branch is updated 😄

**Comment by dperetti** [comment]
Doesn't work : the path must be unquoted [here](https://github.com/blacktorn/django-storage-swift/pull/80/commits/a35f437cdaeccf66f3b4faf2934942b2d139f01d#diff-d24180dedfb00837ffde43d8c34067cfR358) because it was quoted [here](https://github.com/blacktorn/django-storage-swift/pull/80/commits/a35f437cdaeccf66f3b4faf2934942b2d139f01d#diff-d24180dedfb00837ffde43d8c34067cfR353) !

**Comment by einarf** [comment]
fixed

**Comment by dperetti** [comment]
Nope : 

> unquote() got an unexpected keyword argument 'encoding'

**Comment by einarf** [comment]
Must be a python 2 thing

**Comment by einarf** [comment]
Fixed. all good things are 5?

**Comment by dperetti** [comment]
That was the one ! 👍

**Comment by einarf** [comment]
.. and I added unit test to verify the generated temp-url key.

Please close this issue if there is nothing more to add.

**Comment by einarf** [comment]
@blacktorn @dperetti Can any one you close this issue?
