### ISSUE TITLE
Should require python-swiftclient 2.2.0 or later

### ISSUE THREAD

**Issue by Roadmaster** [blacktorn/django-storage-swift#88]
https://github.com/blacktorn/django-storage-swift/commit/e2618ea1266f5f0a7368081ff1c33cf1b0117f0b introduces use of swiftclient.utils.generate_temp_url which was added in python-swiftclient 2.2.0, so the setup.py should be updated to require >=2.2.0 instead of the current >=1.4.0.

**Comment by einarf** [comment]
Yep. That one was my bad 😄
